# Generated by Django 3.2.3 on 2021-05-19 13:32

import autoslug.fields
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('acctmang', '0001_initial'),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=500)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('unit_amount', models.DecimalField(decimal_places=2, help_text='Price for a unit of this plan', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('roi_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage Value for ROI e.g 50, 10.6, 4.99 etc.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Roi')),
                ('image_url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='investments',
            name='address',
        ),
        migrations.RemoveField(
            model_name='investments',
            name='day',
        ),
        migrations.RemoveField(
            model_name='investments',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='investments',
            name='name',
        ),
        migrations.RemoveField(
            model_name='investments',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='investments',
            name='platform',
        ),
        migrations.AddField(
            model_name='investments',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investments',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investments',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investments',
            name='roi_metadata',
            field=models.JSONField(default=dict, help_text='This Contains breakdown of the Current ROI percentage during creation and the expected Returns'),
        ),
        migrations.AddField(
            model_name='investments',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acctmang.user'),
        ),
        migrations.AlterField(
            model_name='investments',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='investments',
            name='end',
            field=models.CharField(blank=True, editable=False, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='investor',
            field=models.CharField(editable=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='investments',
            name='plan',
            field=models.CharField(blank=True, editable=False, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='roi',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='start',
            field=models.CharField(blank=True, editable=False, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Complete', 'Complete')], default='Pending', max_length=1000),
        ),
        migrations.AddField(
            model_name='investments',
            name='investment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investments.investmentplan'),
        ),
    ]
