# Generated by Django 3.2.3 on 2021-05-17 14:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_auto_20210517_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
