# Generated by Django 3.2.3 on 2021-05-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_alter_investments_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investments',
            name='phone',
        ),
    ]
