# Generated by Django 3.2.3 on 2021-05-17 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_remove_investments_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='investment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investments.investmentplan'),
        ),
    ]
