# Generated by Django 3.2.3 on 2021-05-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_alter_investments_investment_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investments',
            name='investment_plan',
        ),
    ]
