# Generated by Django 3.2.3 on 2021-05-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('regdate', models.CharField(max_length=1000)),
                ('birth', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=1000)),
                ('bank', models.CharField(max_length=1000)),
                ('accnumber', models.CharField(max_length=1000)),
                ('refcode', models.CharField(max_length=1000)),
                ('sponsor', models.CharField(max_length=1000)),
                ('refactive', models.CharField(max_length=1000)),
                ('refwallet', models.CharField(max_length=1000)),
                ('blaze_wallet', models.CharField(max_length=1000)),
                ('bbb_plan', models.CharField(max_length=1000)),
                ('kin_name', models.CharField(max_length=1000)),
                ('kin_email', models.CharField(max_length=1000)),
                ('kin_phone', models.CharField(max_length=1000)),
                ('kin_rel', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
